# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49d82e043af6fbedd624f0cc3aec8656b5a68216d5cfded59f8a032f47ed5ab8b6c8a11b58a943f423c44e09f234cabc2c208a6625e6d10722090775851a5360

test:
  secret_key_base: 132db2072bbe3220d0205c6146a4e77f05c9013f46133cf78a0a301bb6cb95e0259ac66022f79b3a324bacfc60fff7de0ecbe7955580a4f8c5500088c6f34243

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
